### ISSUE TITLE
Trouble with the feature request action

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-github-triage-actions#299]
Hello, the feature-request action has been failing for us as of the last two days.

The first failure was https://github.com/microsoft/vscode-azureresourcegroups/actions/runs/10156591104/job/28085246171. And it looked like we needed to add the newly required repo and owner inputs. I did that in https://github.com/microsoft/vscode-azureresourcegroups/pull/888 but now we have a new error: https://github.com/microsoft/vscode-azureresourcegroups/actions/runs/10184534085/job/28172096293

The message is very odd because it says the bot is being run on an issue number that doesn't exist within that repo. Any help is appreciated.

**Comment by bhavyaus** [comment]
@alexweininger could you please rerun your workflow? I've reverted a change we made while migrating our workflows which should fix the issue.

**Comment by alexweininger** [comment]
@bhavyaus thank you, it's working again

**Comment by bwateratmsft** [comment]
I'm still seeing these failing @alexweininger. Do we need to pick up changes in the other repositories?

**Comment by alexweininger** [comment]
@bwateratmsft the only thing I changed was https://github.com/microsoft/vscode-azureresourcegroups/pull/888. Are the other repositories using the latest version of this action?

**Comment by bwateratmsft** [comment]
Can you make the same PR to the following repos?
vscode-azurestorage
vscode-azurestaticwebapps
vscode-azureappservice
vscode-cosmosdb
